# Generated by Django 6.0.5 on 2026-05-25 12:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('quote', 4), ('testimonial', 8), ('feature', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Quote text'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Attribution', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('attribution', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Testimonial text'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Author name'}), 7: ('wagtail.blocks.CharBlock', (), {'label': "Role / description (e.g. 'Mother of two')", 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 5), ('author_name', 6), ('author_role', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Icon (emoji or symbol)', 'max_length': 10}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Description'}), 12: ('wagtail.blocks.StructBlock', [[('icon', 9), ('heading', 10), ('text', 11)]], {})}),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('quote', 4), ('testimonial', 8), ('feature', 12)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Quote text'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Attribution', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('attribution', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Testimonial text'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Author name'}), 7: ('wagtail.blocks.CharBlock', (), {'label': "Role / description (e.g. 'Mother of two')", 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 5), ('author_name', 6), ('author_role', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Icon (emoji or symbol)', 'max_length': 10}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Description'}), 12: ('wagtail.blocks.StructBlock', [[('icon', 9), ('heading', 10), ('text', 11)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('quote', 4), ('testimonial', 8), ('feature', 12)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Quote text'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Attribution', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('attribution', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Testimonial text'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Author name'}), 7: ('wagtail.blocks.CharBlock', (), {'label': "Role / description (e.g. 'Mother of two')", 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 5), ('author_name', 6), ('author_role', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Icon (emoji or symbol)', 'max_length': 10}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Description'}), 12: ('wagtail.blocks.StructBlock', [[('icon', 9), ('heading', 10), ('text', 11)]], {})}),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('quote', 4), ('testimonial', 8), ('feature', 12)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Quote text'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Attribution', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('attribution', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Testimonial text'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Author name'}), 7: ('wagtail.blocks.CharBlock', (), {'label': "Role / description (e.g. 'Mother of two')", 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 5), ('author_name', 6), ('author_role', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Icon (emoji or symbol)', 'max_length': 10}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Description'}), 12: ('wagtail.blocks.StructBlock', [[('icon', 9), ('heading', 10), ('text', 11)]], {})}),
        ),
    ]
